### PR TITLE
Revised script to show uptime.com downtime

### PR DESCRIPTION
**Pull request by rajpalc7**
Signed-off-by: Rajpal Chauhan <rajpal.chauhan@gov.bc.ca>

### CODE REVIEW

**Review by ShellyXueHan — CHANGES_REQUESTED** [review]
Hi Raj, please don't start a new webhook script since the difference is just adding in a downtime period. You can update the original script and add in comment there to specify what the code block does. So teams can choose to either use it or simply comment it out when they don't need it.

**Comment by WadeBarnes** [comment]
@ShellyXueHan, I just discussed the same thing with @rajpalc7.  He'll be updating the PR to be an update to the original script.

**Comment by WadeBarnes** [comment]
I can't see anyone not wanting a summary of the downtime duration.

**Review by ShellyXueHan — APPROVED** [review]
LGTM! thanks @rajpalc7

**Pull request merged**
